-- MySQL Script generated by MySQL Workbench
-- 06/13/15 23:36:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema my_hypermediagym
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_hypermediagym
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_hypermediagym` DEFAULT CHARACTER SET latin1 ;
USE `my_hypermediagym` ;

-- -----------------------------------------------------
-- Table `my_hypermediagym`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_hypermediagym`.`category` ;

CREATE TABLE IF NOT EXISTS `my_hypermediagym`.`category` (
  `category_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `description` TINYTEXT NOT NULL,
  `origins` TINYTEXT NOT NULL,
  `benefits` TINYTEXT NOT NULL,
  `meant_for` TINYTEXT NOT NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_hypermediagym`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_hypermediagym`.`room` ;

CREATE TABLE IF NOT EXISTS `my_hypermediagym`.`room` (
  `room_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `location` TINYTEXT NOT NULL,
  PRIMARY KEY (`room_id`),
  UNIQUE INDEX `room_name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_hypermediagym`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_hypermediagym`.`course` ;

CREATE TABLE IF NOT EXISTS `my_hypermediagym`.`course` (
  `course_id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(40) NOT NULL,
  `description` TEXT NOT NULL,
  `target` TEXT NOT NULL,
  `level` VARCHAR(40) NOT NULL,
  `course_category_id` INT(11) NOT NULL,
  `course_room_id` INT(11) NOT NULL,
  `schedule` TEXT NOT NULL,
  PRIMARY KEY (`course_id`),
  UNIQUE INDEX `course_title` (`title` ASC),
  INDEX `course_category_id` (`course_category_id` ASC),
  INDEX `course_room_id` (`course_room_id` ASC),
  CONSTRAINT `course_category_id`
    FOREIGN KEY (`course_category_id`)
    REFERENCES `my_hypermediagym`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `course_room_id`
    FOREIGN KEY (`course_room_id`)
    REFERENCES `my_hypermediagym`.`room` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_hypermediagym`.`instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_hypermediagym`.`instructor` ;

CREATE TABLE IF NOT EXISTS `my_hypermediagym`.`instructor` (
  `instructor_id` INT(11) NOT NULL AUTO_INCREMENT,
  `bio` TINYTEXT NOT NULL,
  `qualifications` TINYTEXT NOT NULL,
  `prizes_and_awards` TINYTEXT NOT NULL,
  `instructor_of_the_month` TINYINT(1) NOT NULL,
  PRIMARY KEY (`instructor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_hypermediagym`.`course_instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_hypermediagym`.`course_instructor` ;

CREATE TABLE IF NOT EXISTS `my_hypermediagym`.`course_instructor` (
  `course_instructor_id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_course_id` INT(11) NOT NULL,
  `fk_instructor_id` INT(11) NOT NULL,
  PRIMARY KEY (`course_instructor_id`),
  INDEX `fk_course_id` (`fk_course_id` ASC),
  INDEX `fk_instructor_id` (`fk_instructor_id` ASC),
  CONSTRAINT `fk_course_id`
    FOREIGN KEY (`fk_course_id`)
    REFERENCES `my_hypermediagym`.`course` (`course_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_instructor_id`
    FOREIGN KEY (`fk_instructor_id`)
    REFERENCES `my_hypermediagym`.`instructor` (`instructor_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_hypermediagym`.`equipment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_hypermediagym`.`equipment` ;

CREATE TABLE IF NOT EXISTS `my_hypermediagym`.`equipment` (
  `equipment_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  `description` TINYTEXT NOT NULL,
  `image_path` TINYTEXT NOT NULL,
  PRIMARY KEY (`equipment_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_hypermediagym`.`homepage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_hypermediagym`.`homepage` ;

CREATE TABLE IF NOT EXISTS `my_hypermediagym`.`homepage` (
  `homepage_id` INT(11) NOT NULL AUTO_INCREMENT,
  `header_image_path` TEXT NOT NULL,
  `general_description` TEXT NOT NULL,
  `founder_video_path` TEXT NOT NULL,
  `founder_description` TEXT NOT NULL,
  PRIMARY KEY (`homepage_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_hypermediagym`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_hypermediagym`.`location` ;

CREATE TABLE IF NOT EXISTS `my_hypermediagym`.`location` (
  `location_id` INT(11) NOT NULL AUTO_INCREMENT,
  `address` TINYTEXT NOT NULL,
  `how_to_get_here` TINYTEXT NOT NULL,
  `lat` FLOAT NOT NULL,
  `long` FLOAT NOT NULL,
  PRIMARY KEY (`location_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `my_hypermediagym`.`room_gallery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `my_hypermediagym`.`room_gallery` ;

CREATE TABLE IF NOT EXISTS `my_hypermediagym`.`room_gallery` (
  `room_gallery_id` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_room_id` INT(11) NOT NULL,
  `image_path` TINYTEXT NOT NULL,
  PRIMARY KEY (`room_gallery_id`),
  INDEX `fk_room_id` (`fk_room_id` ASC),
  CONSTRAINT `fk_room_id`
    FOREIGN KEY (`fk_room_id`)
    REFERENCES `my_hypermediagym`.`room` (`room_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
